# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Lagranjoon'
description:	       'a minimalist Jekyll theme'
author:              'Jhon Doe'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml



# Site Settings

# Comments
## Select a service and change 'comments' to true for enable that comments system comments
disqus: # Más info en https://disqus.com
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'
utterances: # Más info en https://utteranc.es
  comments: false
  utterances_repo: "[owner]/[repo]"
  utterances_issue-term: "url"
  utterances_issue: "" # Leave in blank if you don't want this function
  utterances_theme: "github-light"

# Google Analitycs
google-ID: '' # If you are not using Google Analytics, please change 'google-ID' to an empty string

# Menu
menu:
- {name: 'Home',        url: ''}
- {name: 'About',       url: 'about'}
- {name: 'Archive',     url: 'archive'}
- {name: 'Contact',     url: 'contact'}
## Icons
### Available social icons are powered by Fork Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com'}
- {icon: 'twitter',    link: 'https://twitter.com'}
- {icon: 'linkedin',   link: 'http://linkedin.com'}
- {icon: 'envelope',   link: 'mailto:jhon@example.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'

# Footer
footer: ""
